"use client";

import { CheckCircle2, ChevronLeft, ChevronRight, Download, FileImage, FileText, ReceiptText, RefreshCw, Search } from "lucide-react";
import { useMemo, useState } from "react";

export type DocumentRow = { id: string; title: string; project: string; investor: string; type: "receipt" | "report" | "photo"; date: string; url: string };
const icons = { receipt: ReceiptText, report: FileText, photo: FileImage };

export function DocumentTable({ rows, canSync = false }: { rows: DocumentRow[]; canSync?: boolean }) {
  const [query, setQuery] = useState(""); const [type, setType] = useState("all"); const [page, setPage] = useState(1); const [syncing, setSyncing] = useState(false); const [synced, setSynced] = useState(false); const pageSize = 7;
  const filtered = useMemo(() => rows.filter((row) => (type === "all" || row.type === type) && `${row.title} ${row.project} ${row.investor}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => b.date.localeCompare(a.date)), [rows, query, type]);
  const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const visible = filtered.slice((Math.min(page, pages) - 1) * pageSize, Math.min(page, pages) * pageSize);
  const sync = () => { setSyncing(true); setSynced(false); setTimeout(() => { setSyncing(false); setSynced(true); }, 1100); };
  return <section className="panel overflow-hidden"><div className="flex flex-col gap-3 border-b border-[#2c2c54]/60 p-4 lg:flex-row lg:items-center"><div className="relative max-w-sm flex-1"><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#707095]" /><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} className="input-shell h-9 pl-9 pr-3 text-[11px]" placeholder="Search documents…" /></div><select value={type} onChange={(event) => { setType(event.target.value); setPage(1); }} className="input-shell h-9 w-auto px-3 text-[11px]"><option value="all">All file types</option><option value="receipt">Receipts</option><option value="report">Reports</option><option value="photo">Photos</option></select>{canSync && <button onClick={sync} className="secondary-button px-3">{synced ? <CheckCircle2 size={13} className="text-[#4fe8b8]" /> : <RefreshCw size={13} className={syncing ? "animate-spin" : ""} />}{syncing ? "Syncing…" : synced ? "Up to date" : "Sync GitHub"}</button>}</div>
    <div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left"><thead className="bg-[#171734] text-[9px] uppercase tracking-wider text-[#747499]"><tr><th className="px-5 py-3 font-medium">Document</th><th className="px-5 py-3 font-medium">Project</th><th className="px-5 py-3 font-medium">Investor</th><th className="px-5 py-3 font-medium">Uploaded</th><th className="px-5 py-3 text-right font-medium">File</th></tr></thead><tbody>{visible.map((row, index) => { const Icon = icons[row.type]; return <tr key={row.id} className={`table-row border-t border-[#2c2c54]/40 text-[11px] ${index % 2 ? "bg-[#181837]/40" : ""}`}><td className="px-5 py-3.5"><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-[#272753] text-[#9f93ff]"><Icon size={14} /></span><div><p className="max-w-[290px] truncate font-medium">{row.title}</p><p className="mt-1 text-[9px] capitalize text-[#77779a]">{row.type}</p></div></div></td><td className="px-5 py-3.5 text-[#a0a0ba]">{row.project}</td><td className="px-5 py-3.5 text-[#8888aa]">{row.investor}</td><td className="tabular px-5 py-3.5 text-[#8888aa]">{row.date}</td><td className="px-5 py-3.5 text-right"><a href={row.url} className="inline-grid size-8 place-items-center rounded-lg bg-[#252550] text-[#aaa0ff] hover:bg-[#6c5ce7] hover:text-white"><Download size={13} /></a></td></tr>; })}</tbody></table></div>
    {visible.length === 0 && <div className="p-12 text-center text-[11px] text-[#8181a3]">No documents match these filters.</div>}
    <div className="flex items-center justify-between border-t border-[#2c2c54]/60 px-5 py-3"><p className="text-[9px] text-[#77779a]">Showing {visible.length} of {filtered.length} documents</p><div className="flex items-center gap-2"><button disabled={page <= 1} onClick={() => setPage((value) => value - 1)} className="grid size-7 place-items-center rounded-lg bg-[#222249] disabled:opacity-30"><ChevronLeft size={13} /></button><span className="text-[9px] text-[#8585a7]">{Math.min(page, pages)} / {pages}</span><button disabled={page >= pages} onClick={() => setPage((value) => value + 1)} className="grid size-7 place-items-center rounded-lg bg-[#222249] disabled:opacity-30"><ChevronRight size={13} /></button></div></div>
  </section>;
}
