"use client";

import { Check, Save } from "lucide-react";
import { useState } from "react";
import type { Session } from "@/lib/types";

export function SettingsForm({ session }: { session: Session }) {
  const [saved, setSaved] = useState(false);
  return <div className="grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><section className="panel p-5"><p className="text-[13px] font-semibold">Contact information</p><p className="mt-1 text-[10px] text-[#8181a3]">Used for account and distribution notices.</p><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-[10px] text-[#8e8ead]">Full name<input className="input-shell mt-2 h-10 px-3 text-[11px]" defaultValue={session.name} /></label><label className="text-[10px] text-[#8e8ead]">Email address<input className="input-shell mt-2 h-10 px-3 text-[11px]" defaultValue={session.email} /></label><label className="text-[10px] text-[#8e8ead]">Phone number<input className="input-shell mt-2 h-10 px-3 text-[11px]" defaultValue="+52 55 0000 1840" /></label><label className="text-[10px] text-[#8e8ead]">Bank details<input className="input-shell mt-2 h-10 px-3 text-[11px]" defaultValue="Account ending •••• 4108" /></label></div><button onClick={() => { setSaved(true); setTimeout(() => setSaved(false), 1600); }} className="primary-button mt-6 px-4">{saved ? <Check size={14} /> : <Save size={14} />}{saved ? "Changes saved" : "Save changes"}</button></section><section className="panel p-5"><p className="text-[13px] font-semibold">Notifications</p><p className="mt-1 text-[10px] text-[#8181a3]">Choose the updates you receive.</p><div className="mt-5 space-y-3">{[["Distribution notices", "When a new payment is posted", true], ["Construction updates", "Milestone and progress changes", true], ["New documents", "Reports and receipts added", true], ["Monthly digest", "Portfolio summary by email", false]].map(([label, detail, checked]) => <label key={String(label)} className="flex items-center gap-3 rounded-xl bg-[#20204a]/70 p-3"><input type="checkbox" defaultChecked={Boolean(checked)} className="size-4 accent-[#6c5ce7]" /><span><span className="block text-[10px] font-medium">{label}</span><span className="mt-1 block text-[9px] text-[#77779a]">{detail}</span></span></label>)}</div></section></div>;
}
